### ISSUE TITLE
Basic application and infra setup with CI/CD

### ISSUE THREAD

**Issue by PeterAronZentai** [MediaBox-Solutions/mediabox#1]
Our first iterations goal is to have some simple web apps running from the cloud. the App will implement the [Login feature](https://github.com/MediaBox-Solutions/mediabox/issues/2) to provide access to the [ImageLibrary app](https://github.com/MediaBox-Solutions/mediabox/issues/5). The ImageLibrary app will implement general look and feel, plus the left side. 

- [x] Based on AWS Serverless Application Model
- [x] Capability to service web pages
   - rendered with Next.js - hosted in one single lambda function
   - one lambda per route is also an option to look into
   - AWS API Gateway if configured
- [x] Capability: service REST API endpoints - via Express - again hosted in lambda functions
- [x] Capability: a single environment now (just DEV but not STAGE and PROD)
- [x] Capability: automatic deployment on code change

**Comment by PeterAronZentai** [comment]
completed
